name: Client CI

on:
  pull_request:
    paths:
      - 'client/**'
  push:
    paths:
      - 'client/**'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Run Client CI (sleep)
        run: sleep 60
