name: Merge Queue Pipeline

# This workflow conditionally runs which workflows should run as part of the merge queue pipeline
# Since this gets invoked for every pull request attempting to merge with the target branch ('dev')
# it is required to run and cannot be skipped using GA event paths.

on:
  merge_group:
  pull_request:
  workflow_dispatch:

jobs:
  check-paths:
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v3
        id: filter-steps
        with:
          base: ${{ github.event.pull_request.base.ref || github.event.merge_group.base_ref }}
          ref: ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref }}
          filters: |
            server-paths:
              - 'server/**'

  server-ci:
    needs: [check-paths]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo needs.check-paths.outputs: ${{needs.check-paths.outputs}}

  #    if: needs.check-paths.outputs.server-paths == 'true'
#    uses: ./.github/workflows/server-ci-tests.yml

# This is the job we use as the required status check in the branch protection settings, use it to refer
# to additional jobs which can reference separate workflows via `needs: [required-job]`
  merge-queue-pipeline-success:
    name: Merge Queue Pipeline Success
    if: github.event_name == 'merge_group' && success()
    needs: [check-paths, server-ci]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Merge Queue Pipeline Finished"
