name: Merge Queue Pipeline

on:
  merge_group:
  workflow_dispatch:

jobs:
  check-paths:
    name: Run Server CI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v3
        with:
          base: ${{ github.event.pull_request.base.ref || github.event.merge_group.base_ref }}
          ref: ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref }}
          filters: |
            server-paths:
              - 'server/**'

  server-ci:
    needs: check-paths
    if: needs.check-paths.outputs.server-paths == 'true'
    uses: ./.github/workflows/server-ci-tests.yml
