name: 'Composite Deploy Action'
description: 'Run Deploy process'
runs:
  using: 'composite'
  steps:
    - name: Run Deploy
      run: |
        echo "Running Deploy..."
        sleep 60
      shell: bash