name: Server CI CD

on:
  workflow_dispatch:
  workflow_call:

jobs:
  server-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Run Server CI
        if: Success()
        uses: './workflows/server-ci.yml'
        with:
          stage: 'local'
      - name: Run Server Deploy
        if: ${{ github.event_name == 'merge_group' }}
        uses: './workflows/server-cd.yml'
      - name: Run Server CI (int)
        if: ${{ github.event_name == 'merge_group' }} && Success()
        uses: './workflows/server-ci.yml'
        with:
          stage: 'int'

