name: Server CI

on:
  pull_request:
  merge_group:

jobs:
  ci:
    name: Run Server CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v3
        id: paths
        with:
          base: ${{ github.event.pull_request.base.ref || github.event.merge_group.base_ref }}
          ref: ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref }}
          filters: |
            server-service:
              - 'server/**'

      - name: Run Server CI (conditional sleep)
        # run only if some file in 'server' folder was changed
        if: steps.paths.outputs.server-service == 'true'
        run: |
          if [ "${{  github.event_name }}" == "merge_group" ]; then
            echo "Running in merge queue..."
            sleep 60
            echo "Failing after sleep for demonstration"
            exit 1
          else
            echo "Regular CI run..."
            sleep 60
          fi
