name: Server CI

on:
  pull_request:
    paths:
      - 'server/**'
  push:
    paths:
      - 'server/**'
  merge_group:

jobs:
  ci:
    name: Run Server CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Server CI (conditional sleep)
        run: |
          if [ "${{ github.event.label.name }}" == "merge_queue" ]; then
            echo "Running in merge queue..."
            sleep 60
            echo "Failing after sleep for demonstration"
            exit 1
          else
            echo "Regular CI run..."
            sleep 60
          fi
        env:
          MERGE_QUEUE: ${{ github.event.label.name }}
