name: Server CI

on:
  pull_request:
    paths:
      - 'server/**'
  push:
    branches:
      - 'gh-readonly-queue/main/**'
    paths:
      - 'server/**'
  merge_group:
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Run Server CI (sleep)
        run: sleep 60
