name: Server CI Tests

on:
  pull_request:
    paths:
      - 'server/**'
  workflow_dispatch:
  workflow_call:

jobs:
  server-ci:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ "${{  github.event_name }}" == "merge_group" ]; then
            echo "Running in merge queue..."
            sleep 120
            echo "Failing after sleep for demonstration"
            exit 1
          else
            echo "Regular CI run..."
            sleep 30
          fi
