name: 'Composite CI Action'
on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
        description: 'Environment to run CI in'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run CI
        run: |
          echo "Running CI in ${{ inputs.stage }}..."
          if [ "${{ inputs.stage }}" == "int" ]; then
            sleep 60
          else
            sleep 30
          fi
        shell: bash