name: Server CI CD

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

jobs:
  server-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Type: ${{ github.event }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Base Ref: ${{ github.base_ref }}"
          echo "Head Ref: ${{ github.head_ref }}"
          sleep 10
          exit 0
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Run Server CI
#        if: Success()
#        uses: ./.github/workflows/actions/server-ci
#        with:
#          stage: 'local'
#      - name: Run Server Deploy
#        if: ${{ github.event_name == 'merge_group' && Success() }}
#        uses: ./.github/workflows/actions/server-cd
#      - name: Run Server CI (int)
#        if: ${{ github.event_name == 'merge_group' && Success() }}
#        uses: ./.github/workflows/actions/server-ci
#        with:
#          stage: 'int'

