name: Server CI

on:
  pull_request:
    paths:
      - 'server/**'
  push:
    paths:
      - 'server/**'
  merge_group:
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Server CI (sleep)
        run: sleep 60
