name: Server CI

on:
  pull_request:
    paths:
      - 'server/**'
  push:
    paths:
      - 'server/**'
  merge_group:

jobs:
  ci:
    name: Run Server CI
    runs-on: ubuntu-latest
    steps:
      - name: Run Server CI (sleep)
        run: sleep 60
