name: 'Composite Deploy Action'
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Deploy
        run: |
          echo "Running Deploy..."
          sleep 60
        shell: bash